chore(deps): upgrade all the things and adjust dependbot

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,16 +1,48 @@
 name: Go
-on: [push]
+on:
+  push:
+    paths-ignore:
+      - 'README.md'
+
+concurrency:
+  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
+  cancel-in-progress: true
+
 jobs:
+
   build:
     name: Build
     runs-on: ubuntu-latest
     steps:
-      - name: Set up Go
-        uses: actions/setup-go@v1
+      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
+      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
         with:
-          go-version: 1.19.x
+          go-version-file: 'go.mod'
+          cache: true
         id: go
-      - name: Check out code into the Go module directory
-        uses: actions/checkout@v1
-      - name: CI Tasks
-        run: make ci
+
+      - name: Run linters
+        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
+        with:
+          version: latest
+          skip-go-installation: true
+
+      - name: Install tparse
+        run: go install github.com/mfridman/tparse@latest
+
+      - name: Test
+        env:
+          COVER_OPTS: "-coverprofile=coverage.txt -covermode=atomic"
+          GOFLAGS:  "-v -count=1 -json"
+        run: go test $COVER_OPTS ./... | tparse -all -notests -format markdown >> $GITHUB_STEP_SUMMARY
+
+      - name: Verify git clean
+        shell: bash
+        run: |
+          if [[ -z "$(git status --porcelain)" ]]; then
+            echo "${{ github.repository }} up to date."
+          else
+            echo "${{ github.repository }} is dirty."
+            echo "::error:: $(git status)"
+            exit 1
+          fi
